### PR TITLE
Wish for Rahul Patel

### PR DESCRIPTION
**Pull request by rahulthecreator**

### CODE REVIEW

**Review by monarchwadia — CHANGES_REQUESTED** [review]
Add your desired hair color to the body of your message.

**Comment by rahulthecreator** [comment]
I'll keep it my natural color. Just get my waves all wavy. Straight Stylin'.

**Comment by monarchwadia** [comment]
Great! Add that to your file :-)

**Comment by monarchwadia** [comment]
Congrats on the merge!

**Pull request merged**
